# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.0.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
-   repo: https://github.com/pre-commit/mirrors-yapf
    rev: v0.24.0
    hooks:
    -   id: yapf
-   repo: https://github.com/prettier/prettier
    rev: 1.14.2
    hooks:
    -   id: prettier
-   repo: https://github.com/doublify/pre-commit-go
    rev: 208a4aaa7f86b44e961eaaea526743b920e187a0
    hooks:
    -   id: fmt
    -   id: fix
